language: cpp
os:
  - osx
  - linux

osx_image: xcode7.2

dist: trusty
sudo: required

matrix:
  exclude:
    - os: linux
    - os: osx

  include:
    - os: linux
      env: CONF=linux-gcov CAN_DEPLOY=False

    - os: osx
      env: CONF=osx-package CAN_DEPLOY=True
    - os: linux
      env: CONF=linux-package CAN_DEPLOY=True

    - os: osx
      env: CONF=osx-debug CAN_DEPLOY=False
    - os: osx
      env: CONF=osx-static-debug CAN_DEPLOY=False
    - os: osx
      env: CONF=osx-release CAN_DEPLOY=False

    - os: linux
      env: CONF=linux-debug CAN_DEPLOY=False
    - os: linux
      env: CONF=linux-static-debug CAN_DEPLOY=False
    - os: linux
      env: CONF=linux-release CAN_DEPLOY=False

# Coverity
#    - os: linux
#      env: CONFIG=linux-coverity CAN_DEPLOY=False

before_install:
- export REPOSITORY_NAME=${PWD##*/}
- cd .. && git clone https://github.com/OSSIA/i-score --depth=1 -b master && cd i-score && git submodule update --init --recursive && cp -rf ../$REPOSITORY_NAME base/addons/
- ./base/addons/$REPOSITORY_NAME/tools/travis/deps.sh

script:
- ./tools/travis/build.sh
